x=int(input("enter x value:"))
y=int(input("enter y value:"))
print("the sum is:",x+y)
print("the difference is:",x-y)
print("the product is:",x*y)
print("the division is:",x/y)
print("the remainder is:",x%y)
print("the floor division is:",x//y)
print("the exponent is:",x**y)
