a=int(input("enter a number:"))
b=float(input("enter a number:"))
c=input("enter c value:")
ia=float(a)
ib=str(b)
ic=int(c)
print("integer converted to float:",type(ia))
print("float converted to string:",type(ib))
print("string converted to integer:",type(ic))
