from tkinter import *  
base = Tk()  
base.geometry("500x500")  
base.title("Student Registration Form")  
lb0=Label(base,text="Student Registration Form",fg="red", font=("arial",12))
lb0.place(x=165,y=20)
lb1= Label(base, text="Enter Name", width=10, font=("arial",12))  
lb1.place(x=20, y=70)  
en1= Entry(base)  
en1.place(x=200, y=70)  
lb3= Label(base, text="Enter Roll Number", width=14, font=("arial",12))  
lb3.place(x=19, y=120)  
en3= Entry(base)  
en3.place(x=200, y=120)  
lb5= Label(base, text="Select Gender", width=15, font=("arial",12))  
lb5.place(x=5, y=170)  
vars = IntVar()  
Radiobutton(base, text="Male", padx=5,variable=vars, value=1).place(x=180, y=172)  
Radiobutton(base, text="Female", padx =10,variable=vars, value=2).place(x=240,y=172)  
Radiobutton(base, text="others", padx=15, variable=vars, value=3).place(x=310,y=172)  
list_of_cntry = ("APTT", "PSPW", "ENG", "MAT")  
cv = StringVar()  
drplist= OptionMenu(base, cv, *list_of_cntry)  
drplist.config(width=15)  
cv.set("Select Subject")  
lb2= Label(base, text="Select Subjects", width=13,font=("arial",12))  
lb2.place(x=14,y=215)  
drplist.place(x=200, y=215)  
list_of_sub = ("CS & AI", "CSE", "ECE", "EEE")  
cv1 = StringVar()  
drplist= OptionMenu(base, cv1, *list_of_sub)  
drplist.config(width=15)  
cv1.set("Select Branch")  
lb4= Label(base,text="Se",lb4.place(x=14,y=265)),lect,Branch,width=13,font=("arial",12),drplist.place(x=200,y=265)
lb5= Label(base, text="Select Habies", width=13,font=("arial",12))  
lb5.place(x=14,y=310)
cbtn1 = Checkbutton(text="Cricket")
cbtn1.place(x=200, y=310)
cbtn2 = Checkbutton(text="Tennis")
cbtn2.place(x=280, y=310)
Button(base, text="Click Here", width=10).place(x=200,y=400)  
base.mainloop() 
